server.port=8080
spring.application.name=Subash Portfolio
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
logging.level.com.subash.portfolio=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n